/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  collections: {
    users: User;
    teachers: Teacher;
    subjects: Subject;
    timetable: Timetable;
    assignments: Assignment;
    exams: Exam;
    tags: Tag;
    media: Media;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  db: {
    defaultIDType: string;
  };
  globals: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name: string;
  username?: string | null;
  roles?: ('Admin' | 'Staff' | 'Member')[] | null;
  dateOfBirth?: string | null;
  subject?: ('🌏 Địa' | '🧪 Hoá' | '⚖️ GDKT-PL' | '🎨 Mỹ Thuật' | '🎤 Nhạc') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teachers".
 */
export interface Teacher {
  id: string;
  title: 'Mr.' | 'Ms.';
  name: string;
  phone?: string | null;
  email?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subjects".
 */
export interface Subject {
  id: string;
  name: string;
  code?: string | null;
  teacher?: (string | null) | Teacher;
  isElective?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "timetable".
 */
export interface Timetable {
  id: string;
  applicationDate: string;
  monday?: {
    morning?: {
      period_1?: (string | null) | Subject;
      period_2?: (string | null) | Subject;
      period_3?: (string | null) | Subject;
      period_4?: (string | null) | Subject;
      period_5?: (string | null) | Subject;
    };
    afternoon?: {
      period_1?: (string | null) | Subject;
      period_2?: (string | null) | Subject;
      period_3?: (string | null) | Subject;
      period_4?: (string | null) | Subject;
    };
  };
  tuesday?: {
    morning?: {
      period_1?: (string | null) | Subject;
      period_2?: (string | null) | Subject;
      period_3?: (string | null) | Subject;
      period_4?: (string | null) | Subject;
      period_5?: (string | null) | Subject;
    };
    afternoon?: {
      period_1?: (string | null) | Subject;
      period_2?: (string | null) | Subject;
      period_3?: (string | null) | Subject;
      period_4?: (string | null) | Subject;
    };
  };
  wednesday?: {
    morning?: {
      period_1?: (string | null) | Subject;
      period_2?: (string | null) | Subject;
      period_3?: (string | null) | Subject;
      period_4?: (string | null) | Subject;
      period_5?: (string | null) | Subject;
    };
  };
  thursday?: {
    morning?: {
      period_1?: (string | null) | Subject;
      period_2?: (string | null) | Subject;
      period_3?: (string | null) | Subject;
      period_4?: (string | null) | Subject;
      period_5?: (string | null) | Subject;
    };
    afternoon?: {
      period_1?: (string | null) | Subject;
      period_2?: (string | null) | Subject;
      period_3?: (string | null) | Subject;
      period_4?: (string | null) | Subject;
    };
  };
  friday?: {
    morning?: {
      period_1?: (string | null) | Subject;
      period_2?: (string | null) | Subject;
      period_3?: (string | null) | Subject;
      period_4?: (string | null) | Subject;
      period_5?: (string | null) | Subject;
    };
    afternoon?: {
      period_1?: (string | null) | Subject;
      period_2?: (string | null) | Subject;
      period_3?: (string | null) | Subject;
      period_4?: (string | null) | Subject;
    };
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assignments".
 */
export interface Assignment {
  id: string;
  subject: string | Subject;
  name: string;
  details?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  formattedDetails?: string | null;
  tags?: (string | Tag)[] | null;
  deadline: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: string;
  name: string;
  importance: 'None' | 'Low' | 'Medium' | 'High';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exams".
 */
export interface Exam {
  id: string;
  subject: string | Subject;
  name: string;
  summary?: string | null;
  details?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  formattedDetails?: string | null;
  tags?: (string | Tag)[] | null;
  date: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}