/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    activities: Activity;
    categories: Category;
    homework: Homework;
    subjects: Subject;
    timetable: Timetable;
    users: User;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  globals: {};
}
export interface Activity {
  id: string;
  name: string;
  date: string;
  endDate?: string | null;
  info?: string | null;
  participants?: (string | User)[] | null;
  details?:
    | {
        [k: string]: unknown;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
export interface User {
  id: string;
  name: string;
  roles?: ('admin' | 'staff' | 'lpkl' | 'lpht' | 'lpds' | 'lppt' | 'groupLeader' | 'student')[] | null;
  verified?: boolean | null;
  verificationToken?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password: string | null;
}
export interface Category {
  id: string;
  title?: string | null;
  updatedAt: string;
  createdAt: string;
}
export interface Homework {
  id: string;
  subject?: (string | null) | Subject;
  deadline?: string | null;
  type?: ('BTVN' | 'TX - HS1' | 'GK - HS2') | null;
  description?: string | null;
  notes?: string | null;
  details?:
    | {
        [k: string]: unknown;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
export interface Subject {
  id: string;
  subject?: string | null;
  teacher?: string | null;
  updatedAt: string;
  createdAt: string;
}
export interface Timetable {
  id: string;
  subject?: (string | null) | Subject;
  day?: ('Monday' | 'Tuesday' | 'Wednesday' | 'Thursday' | 'Friday') | null;
  session?: ('Morning' | 'Afternoon') | null;
  period?: ('1' | '2' | '3' | '4' | '5') | null;
  updatedAt: string;
  createdAt: string;
}
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}