/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    activities: Activity;
    categories: Category;
    exams: Exam;
    homework: Homework;
    subjects: Subject;
    timetable: Timetable;
    users: User;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  globals: {};
}
export interface Activity {
  id: string;
  name: string;
  date: string;
  endDate?: string | null;
  info?: string | null;
  participants?: (string | User)[] | null;
  details?:
    | {
        [k: string]: unknown;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
export interface User {
  id: string;
  name: string;
  username?: string | null;
  roles?: ('Admin' | 'Site Staff' | 'Class Moderator' | 'Student')[] | null;
  dateOfBirth?: string | null;
  subject?: ('Arts' | 'Chemistry' | 'Economics and Law' | 'Geography' | 'Music') | null;
  language?: ('Chinese' | 'French' | 'Japanese') | null;
  sports?: ('Aerobics' | 'Air Volleyball' | 'Basketball' | 'Martial Arts') | null;
  verified?: boolean | null;
  verificationToken?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password: string | null;
}
export interface Category {
  id: string;
  title?: string | null;
  updatedAt: string;
  createdAt: string;
}
export interface Exam {
  id: string;
  subject: string | Subject;
  date: string;
  type: 'TX - HS1' | 'GK - HS2' | 'CK - HS3';
  description?: string | null;
  notes?: string | null;
  details?:
    | {
        [k: string]: unknown;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
export interface Subject {
  id: string;
  name: string;
  teacher?: string | null;
  updatedAt: string;
  createdAt: string;
}
export interface Homework {
  id: string;
  name: string;
  subject: string | Subject;
  deadline: string;
  type: 'BTVN' | 'TX - HS1' | 'GK - HS2';
  description?: string | null;
  notes?: string | null;
  details?:
    | {
        [k: string]: unknown;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
export interface Timetable {
  id: string;
  subject: string | Subject;
  periods: {
    periodGroup: {
      day: 'Monday' | 'Tuesday' | 'Wednesday' | 'Thursday' | 'Friday';
      session: 'Morning' | 'Afternoon';
      period: ('1' | '2' | '3' | '4' | '5')[];
    };
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
}
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}